originDirectory: language
targetDirectory: src/locales
hasNoTranslationsFile: true
isVerbatimModuleSyntax: false
isSplit: true
isStrictTypes: false
isFailOnWarning: false
shouldInjectDefaultLanguage: true
isSimplifiedHashMap: true
